
@echo off

REM !!! Generated by the fmp-cli 1.61.0.  DO NOT EDIT!

md MediaCenter\Assets\3rd\fmp-xtc-mediacenter

cd ..\vs2022
dotnet build -c Release

copy fmp-xtc-mediacenter-lib-mvcs\bin\Release\netstandard2.1\*.dll ..\unity2021\MediaCenter\Assets\3rd\fmp-xtc-mediacenter\
